from __future__ import annotations

from contracts.factor_research import FactorResearchSpec, ValidationThreshold

ALPHA158_SOURCE = "Microsoft Qlib Alpha158 (qlib.contrib.data.loader.Alpha158DL)"
ALPHA158_VERSION = "v2026.06"
ALPHA158_FIRST_10 = (
    "KMID",
    "KLEN",
    "KMID2",
    "KUP",
    "KUP2",
    "KLOW",
    "KLOW2",
    "KSFT",
    "KSFT2",
    "OPEN0",
)

ALPHA158_SECOND_10 = (
    "HIGH0",
    "LOW0",
    "VWAP0",
    "ROC5",
    "ROC10",
    "ROC20",
    "ROC30",
    "ROC60",
    "MA5",
    "MA10",
)

ALPHA158_THIRD_10 = (
    "MA20",
    "MA30",
    "MA60",
    "STD5",
    "STD10",
    "STD20",
    "STD30",
    "STD60",
    "BETA5",
    "BETA10",
)

ALPHA158_FOURTH_10 = (
    "BETA20",
    "BETA30",
    "BETA60",
    "RSQR5",
    "RSQR10",
    "RSQR20",
    "RSQR30",
    "RSQR60",
    "RESI5",
    "RESI10",
)

ALPHA158_FIFTH_10 = (
    "RESI20",
    "RESI30",
    "RESI60",
    "MAX5",
    "MAX10",
    "MAX20",
    "MAX30",
    "MAX60",
    "MIN5",
    "MIN10",
)

ALPHA158_SIXTH_10 = (
    "MIN20",
    "MIN30",
    "MIN60",
    "QTLU5",
    "QTLU10",
    "QTLU20",
    "QTLU30",
    "QTLU60",
    "QTLD5",
    "QTLD10",
)

ALPHA158_SEVENTH_10 = (
    "QTLD20",
    "QTLD30",
    "QTLD60",
    "RANK5",
    "RANK10",
    "RANK20",
    "RANK30",
    "RANK60",
    "RSV5",
    "RSV10",
)

ALPHA158_EIGHTH_10 = (
    "RSV20",
    "RSV30",
    "RSV60",
    "IMAX5",
    "IMAX10",
    "IMAX20",
    "IMAX30",
    "IMAX60",
    "IMIN5",
    "IMIN10",
)

ALPHA158_NINTH_10 = (
    "IMIN20",
    "IMIN30",
    "IMIN60",
    "IMXD5",
    "IMXD10",
    "IMXD20",
    "IMXD30",
    "IMXD60",
    "CORR5",
    "CORR10",
)

ALPHA158_TENTH_10 = (
    "CORR20",
    "CORR30",
    "CORR60",
    "CORD5",
    "CORD10",
    "CORD20",
    "CORD30",
    "CORD60",
    "CNTP5",
    "CNTP10",
)

ALPHA158_ELEVENTH_10 = (
    "CNTP20",
    "CNTP30",
    "CNTP60",
    "CNTN5",
    "CNTN10",
    "CNTN20",
    "CNTN30",
    "CNTN60",
    "CNTD5",
    "CNTD10",
)

ALPHA158_TWELFTH_10 = (
    "CNTD20",
    "CNTD30",
    "CNTD60",
    "SUMP5",
    "SUMP10",
    "SUMP20",
    "SUMP30",
    "SUMP60",
    "SUMN5",
    "SUMN10",
)

ALPHA158_THIRTEENTH_10 = (
    "SUMN20",
    "SUMN30",
    "SUMN60",
    "SUMD5",
    "SUMD10",
    "SUMD20",
    "SUMD30",
    "SUMD60",
    "VMA5",
    "VMA10",
)

ALPHA158_FOURTEENTH_10 = (
    "VMA20",
    "VMA30",
    "VMA60",
    "VSTD5",
    "VSTD10",
    "VSTD20",
    "VSTD30",
    "VSTD60",
    "WVMA5",
    "WVMA10",
)

ALPHA158_FIFTEENTH_10 = (
    "WVMA20",
    "WVMA30",
    "WVMA60",
    "VSUMP5",
    "VSUMP10",
    "VSUMP20",
    "VSUMP30",
    "VSUMP60",
    "VSUMN5",
    "VSUMN10",
)

ALPHA158_SIXTEENTH_8 = (
    "VSUMN20",
    "VSUMN30",
    "VSUMN60",
    "VSUMD5",
    "VSUMD10",
    "VSUMD20",
    "VSUMD30",
    "VSUMD60",
)

ALPHA158_BATCHES: dict[str, dict[str, object]] = {
    "batch_01": {
        "batch_title": "Alpha158 批次01：KBar + OPEN0（因子 #1-#10）",
        "factor_index_start": 1,
        "factor_index_end": 10,
        "factors": ALPHA158_FIRST_10,
    },
    "batch_02": {
        "batch_title": "Alpha158 批次02：Price + ROC + MA（因子 #11-#20）",
        "factor_index_start": 11,
        "factor_index_end": 20,
        "factors": ALPHA158_SECOND_10,
    },
    "batch_03": {
        "batch_title": "Alpha158 批次03：MA + STD + BETA（因子 #21-#30）",
        "factor_index_start": 21,
        "factor_index_end": 30,
        "factors": ALPHA158_THIRD_10,
    },
    "batch_04": {
        "batch_title": "Alpha158 批次04：BETA + RSQR + RESI（因子 #31-#40）",
        "factor_index_start": 31,
        "factor_index_end": 40,
        "factors": ALPHA158_FOURTH_10,
    },
    "batch_05": {
        "batch_title": "Alpha158 批次05：RESI + MAX + MIN（因子 #41-#50）",
        "factor_index_start": 41,
        "factor_index_end": 50,
        "factors": ALPHA158_FIFTH_10,
    },
    "batch_06": {
        "batch_title": "Alpha158 批次06：MIN + QTLU + QTLD（因子 #51-#60）",
        "factor_index_start": 51,
        "factor_index_end": 60,
        "factors": ALPHA158_SIXTH_10,
    },
    "batch_07": {
        "batch_title": "Alpha158 批次07：QTLD + RANK + RSV（因子 #61-#70）",
        "factor_index_start": 61,
        "factor_index_end": 70,
        "factors": ALPHA158_SEVENTH_10,
    },
    "batch_08": {
        "batch_title": "Alpha158 批次08：RSV + IMAX + IMIN（因子 #71-#80）",
        "factor_index_start": 71,
        "factor_index_end": 80,
        "factors": ALPHA158_EIGHTH_10,
    },
    "batch_09": {
        "batch_title": "Alpha158 批次09：IMIN + IMXD + CORR（因子 #81-#90）",
        "factor_index_start": 81,
        "factor_index_end": 90,
        "factors": ALPHA158_NINTH_10,
    },
    "batch_10": {
        "batch_title": "Alpha158 批次10：CORR + CORD + CNTP（因子 #91-#100）",
        "factor_index_start": 91,
        "factor_index_end": 100,
        "factors": ALPHA158_TENTH_10,
    },
    "batch_11": {
        "batch_title": "Alpha158 批次11：CNTP + CNTN + CNTD（因子 #101-#110）",
        "factor_index_start": 101,
        "factor_index_end": 110,
        "factors": ALPHA158_ELEVENTH_10,
    },
    "batch_12": {
        "batch_title": "Alpha158 批次12：CNTD + SUMP + SUMN（因子 #111-#120）",
        "factor_index_start": 111,
        "factor_index_end": 120,
        "factors": ALPHA158_TWELFTH_10,
    },
    "batch_13": {
        "batch_title": "Alpha158 批次13：SUMN + SUMD + VMA（因子 #121-#130）",
        "factor_index_start": 121,
        "factor_index_end": 130,
        "factors": ALPHA158_THIRTEENTH_10,
    },
    "batch_14": {
        "batch_title": "Alpha158 批次14：VMA + VSTD + WVMA（因子 #131-#140）",
        "factor_index_start": 131,
        "factor_index_end": 140,
        "factors": ALPHA158_FOURTEENTH_10,
    },
    "batch_15": {
        "batch_title": "Alpha158 批次15：WVMA + VSUMP + VSUMN（因子 #141-#150）",
        "factor_index_start": 141,
        "factor_index_end": 150,
        "factors": ALPHA158_FIFTEENTH_10,
    },
    "batch_16": {
        "batch_title": "Alpha158 批次16：VSUMN + VSUMD（因子 #151-#158）",
        "factor_index_start": 151,
        "factor_index_end": 158,
        "factors": ALPHA158_SIXTEENTH_8,
    },
}

ALPHA158_ALL_FACTORS: tuple[str, ...] = tuple(
    str(factor)
    for batch in ALPHA158_BATCHES.values()
    for factor in batch["factors"]  # type: ignore[index]
)

# qlib truth 对照未达 Spearman>=0.95（2020-01-02~2021-06-11 全市场跑批结果）。
ALPHA158_KNOWN_DEVIATION_FACTORS: frozenset[str] = frozenset(
    {
        "QTLU60",
        "QTLD60",
        "RANK60",
        "RSV60",
        "IMAX60",
        "IMIN20",
        "IMIN30",
        "IMIN60",
        "IMXD30",
        "IMXD60",
        "CORR60",
        "CORD60",
        "CNTP60",
        "CNTN30",
        "CNTN60",
        "CNTD60",
        "SUMP60",
        "SUMN60",
        "SUMD60",
        "WVMA60",
        "VSUMP60",
        "VSUMN60",
        "VSUMD60",
    }
)

# SmartData 可算，但本地 qlib cn_data 缺 $vwap 字段，truth 导出为 SKIP。
ALPHA158_TRUTH_SKIP_FACTORS: frozenset[str] = frozenset({"VWAP0"})

ALPHA158_SAMPLE_SCOPE = (
    "A-share full market after ST/delist/suspend filters; "
    "factor values computed on SmartData DB trade dates (full window); "
    "qlib truth accuracy check uses a separate overlap window (default through 2021-06-11, "
    "extend with --validation-end when cn_data calendar grows)"
)

ALPHA158_COMMON_THRESHOLDS = [
    ValidationThreshold("cross_section_spearman", ">=", 0.95, "与 qlib truth 截面 Spearman 均值不低于 0.95（约 5% 偏差）。"),
    ValidationThreshold("coverage_ratio", ">=", 0.5, "非空覆盖率不低于 50%。"),
]

ALPHA158_FACTOR_DETAILS: dict[str, dict[str, object]] = {
    "KMID": {
        "formula": "($close - $open) / $open",
        "description": "日内实体涨跌幅，相对开盘价归一化。",
        "required_fields": ["open", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "KLEN": {
        "formula": "($high - $low) / $open",
        "description": "日内振幅相对开盘价。",
        "required_fields": ["open", "high", "low"],
        "frequency": "day",
        "neutralization": [],
    },
    "KMID2": {
        "formula": "($close - $open) / ($high - $low + 1e-12)",
        "description": "实体占全日振幅比例。",
        "required_fields": ["open", "high", "low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "KUP": {
        "formula": "($high - Greater($open, $close)) / $open",
        "description": "上影线相对开盘价。",
        "required_fields": ["open", "high", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "KUP2": {
        "formula": "($high - Greater($open, $close)) / ($high - $low + 1e-12)",
        "description": "上影线占全日振幅比例。",
        "required_fields": ["open", "high", "low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "KLOW": {
        "formula": "(Less($open, $close) - $low) / $open",
        "description": "下影线相对开盘价。",
        "required_fields": ["open", "low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "KLOW2": {
        "formula": "(Less($open, $close) - $low) / ($high - $low + 1e-12)",
        "description": "下影线占全日振幅比例。",
        "required_fields": ["open", "high", "low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "KSFT": {
        "formula": "(2 * $close - $high - $low) / $open",
        "description": "收盘价相对全日价格中枢偏移。",
        "required_fields": ["open", "high", "low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "KSFT2": {
        "formula": "(2 * $close - $high - $low) / ($high - $low + 1e-12)",
        "description": "收盘价相对全日价格中枢偏移（振幅归一化）。",
        "required_fields": ["open", "high", "low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "OPEN0": {
        "formula": "$open / $close",
        "description": "开盘价相对收盘价（Alpha158 price 特征，window=0）。",
        "required_fields": ["open", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "HIGH0": {
        "formula": "$high / $close",
        "description": "最高价相对收盘价（Alpha158 price 特征，window=0）。",
        "required_fields": ["high", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "LOW0": {
        "formula": "$low / $close",
        "description": "最低价相对收盘价（Alpha158 price 特征，window=0）。",
        "required_fields": ["low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "VWAP0": {
        "formula": "$vwap / $close",
        "description": "成交均价相对收盘价（Alpha158 price 特征，window=0）。",
        "required_fields": ["vwap", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "ROC5": {
        "formula": "Ref($close, 5) / $close",
        "description": "5 日前收盘价相对今日收盘价（变化率，去量纲）。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "ROC10": {
        "formula": "Ref($close, 10) / $close",
        "description": "10 日前收盘价相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "ROC20": {
        "formula": "Ref($close, 20) / $close",
        "description": "20 日前收盘价相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "ROC30": {
        "formula": "Ref($close, 30) / $close",
        "description": "30 日前收盘价相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "ROC60": {
        "formula": "Ref($close, 60) / $close",
        "description": "60 日前收盘价相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MA5": {
        "formula": "Mean($close, 5) / $close",
        "description": "5 日收盘均价相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MA10": {
        "formula": "Mean($close, 10) / $close",
        "description": "10 日收盘均价相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MA20": {
        "formula": "Mean($close, 20) / $close",
        "description": "20 日收盘均价相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MA30": {
        "formula": "Mean($close, 30) / $close",
        "description": "30 日收盘均价相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MA60": {
        "formula": "Mean($close, 60) / $close",
        "description": "60 日收盘均价相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "STD5": {
        "formula": "Std($close, 5) / $close",
        "description": "5 日收盘价标准差相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "STD10": {
        "formula": "Std($close, 10) / $close",
        "description": "10 日收盘价标准差相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "STD20": {
        "formula": "Std($close, 20) / $close",
        "description": "20 日收盘价标准差相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "STD30": {
        "formula": "Std($close, 30) / $close",
        "description": "30 日收盘价标准差相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "STD60": {
        "formula": "Std($close, 60) / $close",
        "description": "60 日收盘价标准差相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "BETA5": {
        "formula": "Slope($close, 5) / $close",
        "description": "5 日收盘价线性回归斜率相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "BETA10": {
        "formula": "Slope($close, 10) / $close",
        "description": "10 日收盘价线性回归斜率相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "BETA20": {
        "formula": "Slope($close, 20) / $close",
        "description": "20 日收盘价线性回归斜率相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "BETA30": {
        "formula": "Slope($close, 30) / $close",
        "description": "30 日收盘价线性回归斜率相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "BETA60": {
        "formula": "Slope($close, 60) / $close",
        "description": "60 日收盘价线性回归斜率相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RSQR5": {
        "formula": "Rsquare($close, 5)",
        "description": "5 日收盘价线性回归 R²，衡量趋势线性程度。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RSQR10": {
        "formula": "Rsquare($close, 10)",
        "description": "10 日收盘价线性回归 R²。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RSQR20": {
        "formula": "Rsquare($close, 20)",
        "description": "20 日收盘价线性回归 R²。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RSQR30": {
        "formula": "Rsquare($close, 30)",
        "description": "30 日收盘价线性回归 R²。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RSQR60": {
        "formula": "Rsquare($close, 60)",
        "description": "60 日收盘价线性回归 R²。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RESI5": {
        "formula": "Resi($close, 5) / $close",
        "description": "5 日线性回归残差相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RESI10": {
        "formula": "Resi($close, 10) / $close",
        "description": "10 日线性回归残差相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RESI20": {
        "formula": "Resi($close, 20) / $close",
        "description": "20 日线性回归残差相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RESI30": {
        "formula": "Resi($close, 30) / $close",
        "description": "30 日线性回归残差相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RESI60": {
        "formula": "Resi($close, 60) / $close",
        "description": "60 日线性回归残差相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MAX5": {
        "formula": "Max($high, 5) / $close",
        "description": "5 日最高价相对今日收盘价。",
        "required_fields": ["high", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MAX10": {
        "formula": "Max($high, 10) / $close",
        "description": "10 日最高价相对今日收盘价。",
        "required_fields": ["high", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MAX20": {
        "formula": "Max($high, 20) / $close",
        "description": "20 日最高价相对今日收盘价。",
        "required_fields": ["high", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MAX30": {
        "formula": "Max($high, 30) / $close",
        "description": "30 日最高价相对今日收盘价。",
        "required_fields": ["high", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MAX60": {
        "formula": "Max($high, 60) / $close",
        "description": "60 日最高价相对今日收盘价。",
        "required_fields": ["high", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MIN5": {
        "formula": "Min($low, 5) / $close",
        "description": "5 日最低价相对今日收盘价。",
        "required_fields": ["low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MIN10": {
        "formula": "Min($low, 10) / $close",
        "description": "10 日最低价相对今日收盘价。",
        "required_fields": ["low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MIN20": {
        "formula": "Min($low, 20) / $close",
        "description": "20 日最低价相对今日收盘价。",
        "required_fields": ["low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MIN30": {
        "formula": "Min($low, 30) / $close",
        "description": "30 日最低价相对今日收盘价。",
        "required_fields": ["low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "MIN60": {
        "formula": "Min($low, 60) / $close",
        "description": "60 日最低价相对今日收盘价。",
        "required_fields": ["low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "QTLU5": {
        "formula": "Quantile($close, 5, 0.8) / $close",
        "description": "5 日收盘价 80% 分位数相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "QTLU10": {
        "formula": "Quantile($close, 10, 0.8) / $close",
        "description": "10 日收盘价 80% 分位数相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "QTLU20": {
        "formula": "Quantile($close, 20, 0.8) / $close",
        "description": "20 日收盘价 80% 分位数相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "QTLU30": {
        "formula": "Quantile($close, 30, 0.8) / $close",
        "description": "30 日收盘价 80% 分位数相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "QTLU60": {
        "formula": "Quantile($close, 60, 0.8) / $close",
        "description": "60 日收盘价 80% 分位数相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "QTLD5": {
        "formula": "Quantile($close, 5, 0.2) / $close",
        "description": "5 日收盘价 20% 分位数相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "QTLD10": {
        "formula": "Quantile($close, 10, 0.2) / $close",
        "description": "10 日收盘价 20% 分位数相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "QTLD20": {
        "formula": "Quantile($close, 20, 0.2) / $close",
        "description": "20 日收盘价 20% 分位数相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "QTLD30": {
        "formula": "Quantile($close, 30, 0.2) / $close",
        "description": "30 日收盘价 20% 分位数相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "QTLD60": {
        "formula": "Quantile($close, 60, 0.2) / $close",
        "description": "60 日收盘价 20% 分位数相对今日收盘价。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RANK5": {
        "formula": "Rank($close, 5)",
        "description": "5 日收盘价滚动百分位排名。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RANK10": {
        "formula": "Rank($close, 10)",
        "description": "10 日收盘价滚动百分位排名。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RANK20": {
        "formula": "Rank($close, 20)",
        "description": "20 日收盘价滚动百分位排名。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RANK30": {
        "formula": "Rank($close, 30)",
        "description": "30 日收盘价滚动百分位排名。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RANK60": {
        "formula": "Rank($close, 60)",
        "description": "60 日收盘价滚动百分位排名。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RSV5": {
        "formula": "($close - Min($low, 5)) / (Max($high, 5) - Min($low, 5) + 1e-12)",
        "description": "5 日随机指标 RSV。",
        "required_fields": ["high", "low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RSV10": {
        "formula": "($close - Min($low, 10)) / (Max($high, 10) - Min($low, 10) + 1e-12)",
        "description": "10 日随机指标 RSV。",
        "required_fields": ["high", "low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RSV20": {
        "formula": "($close - Min($low, 20)) / (Max($high, 20) - Min($low, 20) + 1e-12)",
        "description": "20 日随机指标 RSV。",
        "required_fields": ["high", "low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RSV30": {
        "formula": "($close - Min($low, 30)) / (Max($high, 30) - Min($low, 30) + 1e-12)",
        "description": "30 日随机指标 RSV。",
        "required_fields": ["high", "low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "RSV60": {
        "formula": "($close - Min($low, 60)) / (Max($high, 60) - Min($low, 60) + 1e-12)",
        "description": "60 日随机指标 RSV。",
        "required_fields": ["high", "low", "close"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMAX5": {
        "formula": "IdxMax($high, 5) / 5",
        "description": "5 日最高价出现位置（1-based）相对窗口长度。",
        "required_fields": ["high"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMAX10": {
        "formula": "IdxMax($high, 10) / 10",
        "description": "10 日最高价出现位置相对窗口长度。",
        "required_fields": ["high"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMAX20": {
        "formula": "IdxMax($high, 20) / 20",
        "description": "20 日最高价出现位置相对窗口长度。",
        "required_fields": ["high"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMAX30": {
        "formula": "IdxMax($high, 30) / 30",
        "description": "30 日最高价出现位置相对窗口长度。",
        "required_fields": ["high"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMAX60": {
        "formula": "IdxMax($high, 60) / 60",
        "description": "60 日最高价出现位置相对窗口长度。",
        "required_fields": ["high"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMIN5": {
        "formula": "IdxMin($low, 5) / 5",
        "description": "5 日最低价出现位置相对窗口长度。",
        "required_fields": ["low"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMIN10": {
        "formula": "IdxMin($low, 10) / 10",
        "description": "10 日最低价出现位置相对窗口长度。",
        "required_fields": ["low"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMIN20": {
        "formula": "IdxMin($low, 20) / 20",
        "description": "20 日最低价出现位置相对窗口长度。",
        "required_fields": ["low"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMIN30": {
        "formula": "IdxMin($low, 30) / 30",
        "description": "30 日最低价出现位置相对窗口长度。",
        "required_fields": ["low"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMIN60": {
        "formula": "IdxMin($low, 60) / 60",
        "description": "60 日最低价出现位置相对窗口长度。",
        "required_fields": ["low"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMXD5": {
        "formula": "(IdxMax($high, 5) - IdxMin($low, 5)) / 5",
        "description": "5 日高低点位置差相对窗口长度。",
        "required_fields": ["high", "low"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMXD10": {
        "formula": "(IdxMax($high, 10) - IdxMin($low, 10)) / 10",
        "description": "10 日高低点位置差相对窗口长度。",
        "required_fields": ["high", "low"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMXD20": {
        "formula": "(IdxMax($high, 20) - IdxMin($low, 20)) / 20",
        "description": "20 日高低点位置差相对窗口长度。",
        "required_fields": ["high", "low"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMXD30": {
        "formula": "(IdxMax($high, 30) - IdxMin($low, 30)) / 30",
        "description": "30 日高低点位置差相对窗口长度。",
        "required_fields": ["high", "low"],
        "frequency": "day",
        "neutralization": [],
    },
    "IMXD60": {
        "formula": "(IdxMax($high, 60) - IdxMin($low, 60)) / 60",
        "description": "60 日高低点位置差相对窗口长度。",
        "required_fields": ["high", "low"],
        "frequency": "day",
        "neutralization": [],
    },
    "CORR5": {
        "formula": "Corr($close, Log($volume+1), 5)",
        "description": "5 日收盘价与对数成交量滚动相关系数。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "CORR10": {
        "formula": "Corr($close, Log($volume+1), 10)",
        "description": "10 日收盘价与对数成交量滚动相关系数。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "CORR20": {
        "formula": "Corr($close, Log($volume+1), 20)",
        "description": "20 日收盘价与对数成交量滚动相关系数。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "CORR30": {
        "formula": "Corr($close, Log($volume+1), 30)",
        "description": "30 日收盘价与对数成交量滚动相关系数。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "CORR60": {
        "formula": "Corr($close, Log($volume+1), 60)",
        "description": "60 日收盘价与对数成交量滚动相关系数。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "CORD5": {
        "formula": "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 5)",
        "description": "5 日价格变化率与成交量变化率滚动相关系数。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "CORD10": {
        "formula": "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 10)",
        "description": "10 日价格变化率与成交量变化率滚动相关系数。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "CORD20": {
        "formula": "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 20)",
        "description": "20 日价格变化率与成交量变化率滚动相关系数。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "CORD30": {
        "formula": "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 30)",
        "description": "30 日价格变化率与成交量变化率滚动相关系数。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "CORD60": {
        "formula": "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 60)",
        "description": "60 日价格变化率与成交量变化率滚动相关系数。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTP5": {
        "formula": "Mean($close>Ref($close, 1), 5)",
        "description": "5 日上涨天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTP10": {
        "formula": "Mean($close>Ref($close, 1), 10)",
        "description": "10 日上涨天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTP20": {
        "formula": "Mean($close>Ref($close, 1), 20)",
        "description": "20 日上涨天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTP30": {
        "formula": "Mean($close>Ref($close, 1), 30)",
        "description": "30 日上涨天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTP60": {
        "formula": "Mean($close>Ref($close, 1), 60)",
        "description": "60 日上涨天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTN5": {
        "formula": "Mean($close<Ref($close, 1), 5)",
        "description": "5 日下跌天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTN10": {
        "formula": "Mean($close<Ref($close, 1), 10)",
        "description": "10 日下跌天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTN20": {
        "formula": "Mean($close<Ref($close, 1), 20)",
        "description": "20 日下跌天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTN30": {
        "formula": "Mean($close<Ref($close, 1), 30)",
        "description": "30 日下跌天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTN60": {
        "formula": "Mean($close<Ref($close, 1), 60)",
        "description": "60 日下跌天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTD5": {
        "formula": "Mean($close>Ref($close, 1), 5)-Mean($close<Ref($close, 1), 5)",
        "description": "5 日上涨天数占比减下跌天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTD10": {
        "formula": "Mean($close>Ref($close, 1), 10)-Mean($close<Ref($close, 1), 10)",
        "description": "10 日上涨天数占比减下跌天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTD20": {
        "formula": "Mean($close>Ref($close, 1), 20)-Mean($close<Ref($close, 1), 20)",
        "description": "20 日上涨天数占比减下跌天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTD30": {
        "formula": "Mean($close>Ref($close, 1), 30)-Mean($close<Ref($close, 1), 30)",
        "description": "30 日上涨天数占比减下跌天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "CNTD60": {
        "formula": "Mean($close>Ref($close, 1), 60)-Mean($close<Ref($close, 1), 60)",
        "description": "60 日上涨天数占比减下跌天数占比。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMP5": {
        "formula": "Sum(Greater($close-Ref($close, 1), 0), 5)/(Sum(Abs($close-Ref($close, 1)), 5)+1e-12)",
        "description": "5 日总涨幅占绝对价格变动比例（类 RSI 上涨分量）。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMP10": {
        "formula": "Sum(Greater($close-Ref($close, 1), 0), 10)/(Sum(Abs($close-Ref($close, 1)), 10)+1e-12)",
        "description": "10 日总涨幅占绝对价格变动比例。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMP20": {
        "formula": "Sum(Greater($close-Ref($close, 1), 0), 20)/(Sum(Abs($close-Ref($close, 1)), 20)+1e-12)",
        "description": "20 日总涨幅占绝对价格变动比例。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMP30": {
        "formula": "Sum(Greater($close-Ref($close, 1), 0), 30)/(Sum(Abs($close-Ref($close, 1)), 30)+1e-12)",
        "description": "30 日总涨幅占绝对价格变动比例。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMP60": {
        "formula": "Sum(Greater($close-Ref($close, 1), 0), 60)/(Sum(Abs($close-Ref($close, 1)), 60)+1e-12)",
        "description": "60 日总涨幅占绝对价格变动比例。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMN5": {
        "formula": "Sum(Greater(Ref($close, 1)-$close, 0), 5)/(Sum(Abs($close-Ref($close, 1)), 5)+1e-12)",
        "description": "5 日总跌幅占绝对价格变动比例（类 RSI 下跌分量）。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMN10": {
        "formula": "Sum(Greater(Ref($close, 1)-$close, 0), 10)/(Sum(Abs($close-Ref($close, 1)), 10)+1e-12)",
        "description": "10 日总跌幅占绝对价格变动比例。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMN20": {
        "formula": "Sum(Greater(Ref($close, 1)-$close, 0), 20)/(Sum(Abs($close-Ref($close, 1)), 20)+1e-12)",
        "description": "20 日总跌幅占绝对价格变动比例。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMN30": {
        "formula": "Sum(Greater(Ref($close, 1)-$close, 0), 30)/(Sum(Abs($close-Ref($close, 1)), 30)+1e-12)",
        "description": "30 日总跌幅占绝对价格变动比例。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMN60": {
        "formula": "Sum(Greater(Ref($close, 1)-$close, 0), 60)/(Sum(Abs($close-Ref($close, 1)), 60)+1e-12)",
        "description": "60 日总跌幅占绝对价格变动比例。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMD5": {
        "formula": "(Sum(Greater($close-Ref($close, 1), 0), 5)-Sum(Greater(Ref($close, 1)-$close, 0), 5))/(Sum(Abs($close-Ref($close, 1)), 5)+1e-12)",
        "description": "5 日涨跌幅度差占绝对价格变动比例。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMD10": {
        "formula": "(Sum(Greater($close-Ref($close, 1), 0), 10)-Sum(Greater(Ref($close, 1)-$close, 0), 10))/(Sum(Abs($close-Ref($close, 1)), 10)+1e-12)",
        "description": "10 日涨跌幅度差占绝对价格变动比例。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMD20": {
        "formula": "(Sum(Greater($close-Ref($close, 1), 0), 20)-Sum(Greater(Ref($close, 1)-$close, 0), 20))/(Sum(Abs($close-Ref($close, 1)), 20)+1e-12)",
        "description": "20 日涨跌幅度差占绝对价格变动比例。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMD30": {
        "formula": "(Sum(Greater($close-Ref($close, 1), 0), 30)-Sum(Greater(Ref($close, 1)-$close, 0), 30))/(Sum(Abs($close-Ref($close, 1)), 30)+1e-12)",
        "description": "30 日涨跌幅度差占绝对价格变动比例。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "SUMD60": {
        "formula": "(Sum(Greater($close-Ref($close, 1), 0), 60)-Sum(Greater(Ref($close, 1)-$close, 0), 60))/(Sum(Abs($close-Ref($close, 1)), 60)+1e-12)",
        "description": "60 日涨跌幅度差占绝对价格变动比例。",
        "required_fields": ["close"],
        "frequency": "day",
        "neutralization": [],
    },
    "VMA5": {
        "formula": "Mean($volume, 5)/($volume+1e-12)",
        "description": "5 日成交量均线相对当日成交量。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VMA10": {
        "formula": "Mean($volume, 10)/($volume+1e-12)",
        "description": "10 日成交量均线相对当日成交量。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VMA20": {
        "formula": "Mean($volume, 20)/($volume+1e-12)",
        "description": "20 日成交量均线相对当日成交量。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VMA30": {
        "formula": "Mean($volume, 30)/($volume+1e-12)",
        "description": "30 日成交量均线相对当日成交量。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VMA60": {
        "formula": "Mean($volume, 60)/($volume+1e-12)",
        "description": "60 日成交量均线相对当日成交量。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSTD5": {
        "formula": "Std($volume, 5)/($volume+1e-12)",
        "description": "5 日成交量标准差相对当日成交量。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSTD10": {
        "formula": "Std($volume, 10)/($volume+1e-12)",
        "description": "10 日成交量标准差相对当日成交量。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSTD20": {
        "formula": "Std($volume, 20)/($volume+1e-12)",
        "description": "20 日成交量标准差相对当日成交量。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSTD30": {
        "formula": "Std($volume, 30)/($volume+1e-12)",
        "description": "30 日成交量标准差相对当日成交量。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSTD60": {
        "formula": "Std($volume, 60)/($volume+1e-12)",
        "description": "60 日成交量标准差相对当日成交量。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "WVMA5": {
        "formula": "Std(Abs($close/Ref($close, 1)-1)*$volume, 5)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 5)+1e-12)",
        "description": "5 日成交量加权价格波动率（变异系数）。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "WVMA10": {
        "formula": "Std(Abs($close/Ref($close, 1)-1)*$volume, 10)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 10)+1e-12)",
        "description": "10 日成交量加权价格波动率（变异系数）。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "WVMA20": {
        "formula": "Std(Abs($close/Ref($close, 1)-1)*$volume, 20)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 20)+1e-12)",
        "description": "20 日成交量加权价格波动率（变异系数）。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "WVMA30": {
        "formula": "Std(Abs($close/Ref($close, 1)-1)*$volume, 30)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 30)+1e-12)",
        "description": "30 日成交量加权价格波动率（变异系数）。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "WVMA60": {
        "formula": "Std(Abs($close/Ref($close, 1)-1)*$volume, 60)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 60)+1e-12)",
        "description": "60 日成交量加权价格波动率（变异系数）。",
        "required_fields": ["close", "volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMP5": {
        "formula": "Sum(Greater($volume-Ref($volume, 1), 0), 5)/(Sum(Abs($volume-Ref($volume, 1)), 5)+1e-12)",
        "description": "5 日成交量增量占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMP10": {
        "formula": "Sum(Greater($volume-Ref($volume, 1), 0), 10)/(Sum(Abs($volume-Ref($volume, 1)), 10)+1e-12)",
        "description": "10 日成交量增量占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMP20": {
        "formula": "Sum(Greater($volume-Ref($volume, 1), 0), 20)/(Sum(Abs($volume-Ref($volume, 1)), 20)+1e-12)",
        "description": "20 日成交量增量占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMP30": {
        "formula": "Sum(Greater($volume-Ref($volume, 1), 0), 30)/(Sum(Abs($volume-Ref($volume, 1)), 30)+1e-12)",
        "description": "30 日成交量增量占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMP60": {
        "formula": "Sum(Greater($volume-Ref($volume, 1), 0), 60)/(Sum(Abs($volume-Ref($volume, 1)), 60)+1e-12)",
        "description": "60 日成交量增量占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMN5": {
        "formula": "Sum(Greater(Ref($volume, 1)-$volume, 0), 5)/(Sum(Abs($volume-Ref($volume, 1)), 5)+1e-12)",
        "description": "5 日成交量减量占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMN10": {
        "formula": "Sum(Greater(Ref($volume, 1)-$volume, 0), 10)/(Sum(Abs($volume-Ref($volume, 1)), 10)+1e-12)",
        "description": "10 日成交量减量占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMN20": {
        "formula": "Sum(Greater(Ref($volume, 1)-$volume, 0), 20)/(Sum(Abs($volume-Ref($volume, 1)), 20)+1e-12)",
        "description": "20 日成交量减量占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMN30": {
        "formula": "Sum(Greater(Ref($volume, 1)-$volume, 0), 30)/(Sum(Abs($volume-Ref($volume, 1)), 30)+1e-12)",
        "description": "30 日成交量减量占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMN60": {
        "formula": "Sum(Greater(Ref($volume, 1)-$volume, 0), 60)/(Sum(Abs($volume-Ref($volume, 1)), 60)+1e-12)",
        "description": "60 日成交量减量占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMD5": {
        "formula": "(Sum(Greater($volume-Ref($volume, 1), 0), 5)-Sum(Greater(Ref($volume, 1)-$volume, 0), 5))/(Sum(Abs($volume-Ref($volume, 1)), 5)+1e-12)",
        "description": "5 日成交量增减差占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMD10": {
        "formula": "(Sum(Greater($volume-Ref($volume, 1), 0), 10)-Sum(Greater(Ref($volume, 1)-$volume, 0), 10))/(Sum(Abs($volume-Ref($volume, 1)), 10)+1e-12)",
        "description": "10 日成交量增减差占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMD20": {
        "formula": "(Sum(Greater($volume-Ref($volume, 1), 0), 20)-Sum(Greater(Ref($volume, 1)-$volume, 0), 20))/(Sum(Abs($volume-Ref($volume, 1)), 20)+1e-12)",
        "description": "20 日成交量增减差占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMD30": {
        "formula": "(Sum(Greater($volume-Ref($volume, 1), 0), 30)-Sum(Greater(Ref($volume, 1)-$volume, 0), 30))/(Sum(Abs($volume-Ref($volume, 1)), 30)+1e-12)",
        "description": "30 日成交量增减差占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
    "VSUMD60": {
        "formula": "(Sum(Greater($volume-Ref($volume, 1), 0), 60)-Sum(Greater(Ref($volume, 1)-$volume, 0), 60))/(Sum(Abs($volume-Ref($volume, 1)), 60)+1e-12)",
        "description": "60 日成交量增减差占绝对成交量变动比例。",
        "required_fields": ["volume"],
        "frequency": "day",
        "neutralization": [],
    },
}


def _alpha158_proof_metadata(factor_name: str) -> dict[str, object]:
    if factor_name in ALPHA158_TRUTH_SKIP_FACTORS:
        return {
            "status": "implemented",
            "implementation_stage": "alpha158_lab",
            "proof_status": "truth_skip",
            "proof_note": "SmartData 可计算；本地 qlib cn_data 缺 $vwap，truth 对照 SKIP。",
        }
    if factor_name in ALPHA158_KNOWN_DEVIATION_FACTORS:
        return {
            "status": "implemented",
            "implementation_stage": "alpha158_lab",
            "proof_status": "partial_proof",
            "proof_note": "2020-01-02~2021-06-11 qlib 对照 Spearman < 0.95；长窗口/位置类因子，可用于生产但非 qlib 完全一致。",
        }
    return {
        "status": "implemented",
        "implementation_stage": "alpha158_lab",
        "proof_status": "full_proof",
    }


def alpha158_specs(factor_names: list[str] | None = None) -> list[FactorResearchSpec]:
    names = list(factor_names or ALPHA158_ALL_FACTORS)
    specs: list[FactorResearchSpec] = []
    for name in names:
        details = ALPHA158_FACTOR_DETAILS[name]
        proof = _alpha158_proof_metadata(name)
        tags = ["alpha158", "qlib", "implemented"]
        if proof["proof_status"] == "partial_proof":
            tags.append("known_deviation")
        if proof["proof_status"] == "truth_skip":
            tags.append("truth_skip")
        specs.append(
            FactorResearchSpec(
                factor_name=name,
                library="Alpha158",
                version=ALPHA158_VERSION,
                display_name=f"Alpha158 {name}",
                factor_id=f"alpha158_{name.lower()}",
                source_document=ALPHA158_SOURCE,
                formula=str(details["formula"]),
                description=str(details["description"]),
                frequency=str(details["frequency"]),
                sample_scope=ALPHA158_SAMPLE_SCOPE,
                required_fields=list(details["required_fields"]),
                neutralization=list(details["neutralization"]),
                validation_targets=ALPHA158_COMMON_THRESHOLDS,
                tags=tags,
                metadata=proof,
            )
        )
    return specs